### ISSUE TITLE
"Not a password" error

### ISSUE THREAD

**Issue by evertoncherman** [corneliudascalu/intellij-decrypt#1]
I want to recovery passwords stored in security.xml , however, independently of master password a I set, I always have as output "Not a password".

First, I don't really know what is my Master Password because I have never set it. I am using Windows 7, so I tried my user login password. I also tried a empty string.

For all cases, I always have "Not a password" for all stored password, except the first one that a I have  "org.apache.commons.codec.DecoderException: Odd number of characters." exception.

Could you help me?

Thanks,
Everton.

**Comment by choobablue** [comment]
I have the same issue, using the decrypter with AndroidStudio 1.0.2, output is:

XML file OK
PASSWORDS
org.apache.commons.codec.DecoderException: Odd number of characters.
	at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:82)
	at org.corneliudascalu.intellijdecrypt.Main.fromHex(Main.java:71)
	at org.corneliudascalu.intellijdecrypt.Main.main(Main.java:53)

It could be that the xml format has changed, as there is an <option name="PASSWORDS"> element that seems to be causing the problems.

I worked around the issue by commenting out that line of XML before running the decrypt CLI and uncommenting it again after I was done. I can probably write a fix if it would help.

**Comment by aweFalafelApps** [comment]
I finally managed to remember my password! (:

**Comment by corneliudascalu** [comment]
@choobablue Yes, a fix would be great. I just can't find the time to investigate the error.

**Comment by evertoncherman** [comment]
@choobablue which was the line you commented out? I am still using Android 0.8.6...

**Comment by evertoncherman** [comment]
I am still stuck on this issue :( could someone help me?

**Comment by choobablue** [comment]
In the file .AndroidStudio/config/options/security.xml there will be an element that looks like <option name="PASSWORDS">, delete or comment out that tag (and the end tag, but leaving it's children) before running the tool (remember to put the element back in when you're done). That's what worked for me.

**Comment by ACluelessProgrammer** [comment]
I'm also having this same problem. I tried messing with the xml code to get it to work, but didn't really get anywhere.  If anyone can help me, that would be a life saver.  I'm running Android studio 1.1.0.

**Comment by lazyeo** [comment]
similar problem

> XML file OK
> 922311d178b9acc26400694a26643e9aec74e4c52141a7838c9b7bf6a34fbd9f
> Not a password
> a305f2e755982933724eaf7f7d24f1d1af3e72224f719c74d236227db4167887
> Not a password
> 474794fc4e89840b5a76d08ee9fbb31b55356ecc3b89ff3280e07aaa902c9186
> test password

I got two "not a password" and a "test password"

Anyone solved this problem?

**Comment by dan-silver** [comment]
I'm also seeing this not a password message with android studio 2.0
