### ISSUE TITLE
Dont working

### ISSUE THREAD

**Issue by Bupyc** [corneliudascalu/intellij-decrypt#4]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/codec/DecoderException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getMethod0(Class.java:2856)
        at java.lang.Class.getMethod(Class.java:1668)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.DecoderException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 6 more

**Comment by kartikarora** [comment]
Getting the same error

**Comment by AlexCzar** [comment]
Launch the app as it is specified in the README, most probably you're forgetting to set the classpath.

**Comment by mnill** [comment]
Just download all files from repo, not only .jar file

**Comment by mdumrauf** [comment]
The issue is clear in the stacktrace. Please read it:

```
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.DecoderException
```

The class that was not found is in `commons-codec-1.9.jar`, which is not bundled together with `intellij-decrypt.jar`. Download or clone the whole repo and execute what the README says inside that folder:

``` bash
✔ ~/projects/java/intellij-decrypt [master|✔] 
19:16 $ tree
.
├── intellijdecrypt.iml
├── intellij-decrypt.jar
├── lib
│   ├── commons-codec-1.9.jar
│   ├── commons-codec-1.9-javadoc.jar
│   └── LICENSE.txt
├── META-INF
│   └── MANIFEST.MF
├── README.md
└── src
    ├── com
    │   └── intellij
    │       └── ide
    │           └── passwordSafe
    │               └── impl
    │                   └── providers
    │                       └── EncryptionUtil.java
    └── org
        └── corneliudascalu
            └── intellijdecrypt
                └── Main.java

12 directories, 9 files
✔ ~/projects/java/intellij-decrypt [master|✔] 
19:16 $ java -classpath .:intellij-decrypt.jar:lib/commons-codec-1.9.jar org.corneliudascalu.intellijdecrypt.Main
-help Display this help message.
-p <password> Specify the password
-f <path> (Optional) specify the path to the security.xml file. Default to ~/.IdeaIC13/config/options/security.xml
✔ ~/projects/java/intellij-decrypt [master|✔] 
19:16 $
```

**Comment by MakerTim** [comment]
java -cp "intellij-decrypt.jar;lib/*" org.corneliudascalu.intellijdecrypt.Main -f ./security.xml -p

This worked for me on Windows
